name = "halopress"
main = ".output/server/index.mjs"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
# NUXT_AUTH_SECRET = "change-me"
# NUXT_AUTH_ORIGIN = "https://yourdomain/api/auth"

[[d1_databases]]
binding = "DB"
database_name = "halopress"
database_id = "REPLACE_ME"
migrations_dir = "server/db/migrations"
